spring:
  datasource:
    url: jdbc:mariadb://testmariadb.cvhjmwimgvcj.us-east-2.rds.amazonaws.com:3306/testmariadb
    username: dbo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update